#!/usr/bin/env python3
"""
build_manifests.py — ONE canonical source, all host-specific manifests.

DO NOT EDIT the output files — they are generated by this script.

Reads 3-surgeons/.claude-plugin/plugin.json as the canonical source and
generates manifests for: Claude Code, Cursor, VS Code, Codex, Gemini.

Usage:
    python3 3-surgeons/scripts/build_manifests.py          # Generate all manifests
    python3 3-surgeons/scripts/build_manifests.py --check  # Verify sync, no writes
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PLUGIN_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_PLUGIN = PLUGIN_ROOT / ".claude-plugin" / "plugin.json"
MARKETPLACE_JSON = PLUGIN_ROOT / ".claude-plugin" / "marketplace.json"

HEADER_JSON = "DO NOT EDIT — generated by scripts/build_manifests.py"
HEADER_TOML = "# DO NOT EDIT — generated by scripts/build_manifests.py"

# Output targets
OUTPUTS: dict[str, Path] = {
    "mcp_json": PLUGIN_ROOT / ".mcp.json",
    "cursor": PLUGIN_ROOT / ".cursor-plugin" / "plugin.json",
    "vscode": PLUGIN_ROOT / ".vscode" / "mcp.json.example",
    "codex": PLUGIN_ROOT / ".codex" / "config.toml.example",
    "gemini": PLUGIN_ROOT / "gemini-extension.json",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def to_json(data: dict) -> str:
    """JSON with non-ASCII preserved and short arrays collapsed to one line."""
    raw = json.dumps(data, indent=2, ensure_ascii=False)

    def _collapse(m: re.Match) -> str:
        items = [s.strip() for s in m.group(1).split(",")]
        joined = ", ".join(items)
        if len(joined) < 100:
            return f"[{joined}]"
        return m.group(0)

    raw = re.sub(r'\[\s*\n((?:\s*"[^"]{0,40}",?\s*\n)+)\s*\]', _collapse, raw)
    return raw + "\n"


# ---------------------------------------------------------------------------
# Canonical source loader
# ---------------------------------------------------------------------------

def load_canonical() -> dict[str, Any]:
    """Load canonical plugin.json into a single dict."""
    if not CANONICAL_PLUGIN.exists():
        print(f"ERROR: canonical manifest not found: {CANONICAL_PLUGIN}", file=sys.stderr)
        sys.exit(1)
    with open(CANONICAL_PLUGIN) as f:
        plugin = json.load(f)

    # Discover skills from marketplace.json (authoritative list)
    skills: list[str] = []
    if MARKETPLACE_JSON.exists():
        with open(MARKETPLACE_JSON) as f:
            mp = json.load(f)
        for p in mp.get("plugins", []):
            for s in p.get("skills", []):
                skills.append(s.rsplit("/", 1)[-1])

    # Discover commands from commands/ directory
    commands: list[str] = []
    cmd_dir = PLUGIN_ROOT / "commands"
    if cmd_dir.is_dir():
        commands = sorted(p.stem for p in cmd_dir.glob("*.md"))

    # Discover agents from agents/ directory
    agents: list[str] = []
    agent_dir = PLUGIN_ROOT / "agents"
    if agent_dir.is_dir():
        agents = sorted(p.stem for p in agent_dir.glob("*.md"))

    # MCP server config
    mcp_servers = plugin.get("mcpServers", {})
    server_name = list(mcp_servers.keys())[0] if mcp_servers else "3-surgeons"
    server_cfg = mcp_servers.get(server_name, {})

    return {
        "name": plugin["name"],
        "displayName": plugin.get("displayName", "3-Surgeons"),
        "description": plugin["description"],
        "version": plugin["version"],
        "author": plugin["author"],
        "homepage": plugin.get("homepage", ""),
        "repository": plugin.get("repository", ""),
        "license": plugin.get("license", "MIT"),
        "keywords": plugin.get("keywords", []),
        "mcp_server_name": server_name,
        "mcp_server": server_cfg,
        "skills": skills,
        "commands": commands,
        "agents": agents,
    }


# ---------------------------------------------------------------------------
# Manifest generators
# ---------------------------------------------------------------------------

def gen_mcp_json(canon: dict[str, Any]) -> str:
    """Generic .mcp.json — uses ${PLUGIN_ROOT} for portability."""
    doc = {
        "_generated": HEADER_JSON,
        "mcpServers": {
            canon["mcp_server_name"]: {
                "command": "${PLUGIN_ROOT}/bin/3surgeons-mcp",
                "args": [],
                "tools": ["*"],
            }
        },
    }
    return to_json(doc)


def gen_cursor(canon: dict[str, Any]) -> str:
    """Cursor plugin.json — same structure with Cursor conventions."""
    doc = {
        "_generated": HEADER_JSON,
        "name": canon["name"],
        "displayName": canon["displayName"],
        "description": canon["description"],
        "version": canon["version"],
        "author": canon["author"],
        "homepage": canon["homepage"],
        "repository": canon["repository"],
        "license": canon["license"],
        "keywords": canon["keywords"],
        "skills": "./skills/",
        "agents": "./agents/",
        "commands": "./commands/",
        "hooks": "./hooks/hooks.json",
        "mcp": "./.mcp.json",
    }
    return to_json(doc)


def gen_vscode(canon: dict[str, Any]) -> str:
    """VS Code .vscode/mcp.json.example — pure MCP server config."""
    doc = {
        "_generated": HEADER_JSON,
        "servers": {
            canon["mcp_server_name"]: {
                "command": "${workspaceFolder}/bin/3surgeons-mcp",
                "args": [],
            }
        },
    }
    return to_json(doc)


def gen_codex(canon: dict[str, Any]) -> str:
    """Codex CLI .codex/config.toml.example."""
    return textwrap.dedent(f"""\
        {HEADER_TOML}
        # Codex MCP config for 3-Surgeons v{canon["version"]}
        # Copy to ~/.codex/config.toml or .codex/config.toml in your project root.
        #
        # Quick install:
        #   codex mcp add 3-surgeons -- /path/to/3-surgeons/bin/3surgeons-mcp

        [mcp_servers."3-surgeons"]
        command = "./bin/3surgeons-mcp"
        args = []
    """)


def gen_gemini(canon: dict[str, Any]) -> str:
    """Gemini CLI extension manifest."""
    doc = {
        "_generated": HEADER_JSON,
        "name": canon["name"],
        "version": canon["version"],
        "description": canon["description"],
        "contextFileName": "GEMINI.md",
        "mcpServers": {
            canon["mcp_server_name"]: {
                "command": "${extensionPath}/bin/3surgeons-mcp",
                "args": [],
                "cwd": "${extensionPath}",
            }
        },
    }
    return to_json(doc)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

GENERATORS: dict[str, callable] = {
    "mcp_json": gen_mcp_json,
    "cursor": gen_cursor,
    "vscode": gen_vscode,
    "codex": gen_codex,
    "gemini": gen_gemini,
}


def generate_all(check: bool = False) -> bool:
    """Generate or check all manifests. Returns True if all in sync."""
    canon = load_canonical()
    print(f"Canonical source: {CANONICAL_PLUGIN.relative_to(PLUGIN_ROOT)}")
    print(f"  name={canon['name']}  version={canon['version']}")
    print()

    all_ok = True

    for key, gen_fn in GENERATORS.items():
        target = OUTPUTS[key]
        expected = gen_fn(canon)
        rel = target.relative_to(PLUGIN_ROOT)

        if check:
            if not target.exists():
                print(f"  [MISSING]  {rel}")
                all_ok = False
            elif target.read_text() != expected:
                print(f"  [DRIFTED]  {rel}")
                all_ok = False
            else:
                print(f"  [ok]       {rel}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected)
            print(f"  [wrote]    {rel}")

    print()
    if check:
        if all_ok:
            print("All manifests in sync.")
        else:
            print(f"FAIL: manifests out of sync. Run without --check to fix.")
    else:
        print(f"Generated {len(GENERATORS)} manifests from {CANONICAL_PLUGIN.name}.")
        print("Commit these files — they should never be hand-edited.")

    return all_ok


def main():
    parser = argparse.ArgumentParser(
        description="Generate host-specific manifests from canonical 3-Surgeons plugin source."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify all manifests are in sync without writing files.",
    )
    args = parser.parse_args()

    ok = generate_all(check=args.check)
    sys.exit(0 if ok or not args.check else 1)


if __name__ == "__main__":
    main()
